-- 1. Create inventory table
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL,
  size INTEGER NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  UNIQUE(product_id, size)
);

-- Enable Row Level Security
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;

-- Allow public read access for anonymous users
CREATE POLICY "Allow public read access" ON inventory
FOR SELECT TO anon
USING (true);

-- RPC helper function to atomically decrement stock on order placement
CREATE OR REPLACE FUNCTION decrement_stock(p_product_id TEXT, p_size INTEGER)
RETURNS VOID AS $$
BEGIN
  UPDATE inventory
  SET stock = GREATEST(0, stock - 1)
  WHERE product_id = p_product_id AND size = p_size;
END;
$$ LANGUAGE plpgsql;

-- 2. Populate table with initial stock of 10 for each product/size combination (38-46)
INSERT INTO inventory (product_id, size, stock) VALUES
  ('golden-goose', 38, 10),
  ('golden-goose', 39, 10),
  ('golden-goose', 40, 10),
  ('golden-goose', 41, 10),
  ('golden-goose', 42, 10),
  ('golden-goose', 43, 10),
  ('golden-goose', 44, 10),
  ('golden-goose', 45, 10),
  ('golden-goose', 46, 10),
  ('puma-speedcat-ballet-red', 38, 10),
  ('puma-speedcat-ballet-red', 39, 10),
  ('puma-speedcat-ballet-red', 40, 10),
  ('puma-speedcat-ballet-red', 41, 10),
  ('puma-speedcat-ballet-red', 42, 10),
  ('puma-speedcat-ballet-red', 43, 10),
  ('puma-speedcat-ballet-red', 44, 10),
  ('puma-speedcat-ballet-red', 45, 10),
  ('puma-speedcat-ballet-red', 46, 10),
  ('puma-speedcat-ballet-black', 38, 10),
  ('puma-speedcat-ballet-black', 39, 10),
  ('puma-speedcat-ballet-black', 40, 10),
  ('puma-speedcat-ballet-black', 41, 10),
  ('puma-speedcat-ballet-black', 42, 10),
  ('puma-speedcat-ballet-black', 43, 10),
  ('puma-speedcat-ballet-black', 44, 10),
  ('puma-speedcat-ballet-black', 45, 10),
  ('puma-speedcat-ballet-black', 46, 10),
  ('new-balance-530', 38, 10),
  ('new-balance-530', 39, 10),
  ('new-balance-530', 40, 10),
  ('new-balance-530', 41, 10),
  ('new-balance-530', 42, 10),
  ('new-balance-530', 43, 10),
  ('new-balance-530', 44, 10),
  ('new-balance-530', 45, 10),
  ('new-balance-530', 46, 10),
  ('boston-birkenstock-clogs-taupe', 38, 10),
  ('boston-birkenstock-clogs-taupe', 39, 10),
  ('boston-birkenstock-clogs-taupe', 40, 10),
  ('boston-birkenstock-clogs-taupe', 41, 10),
  ('boston-birkenstock-clogs-taupe', 42, 10),
  ('boston-birkenstock-clogs-taupe', 43, 10),
  ('boston-birkenstock-clogs-taupe', 44, 10),
  ('boston-birkenstock-clogs-taupe', 45, 10),
  ('boston-birkenstock-clogs-taupe', 46, 10),
  ('campus-00s-core-black', 38, 10),
  ('campus-00s-core-black', 39, 10),
  ('campus-00s-core-black', 40, 10),
  ('campus-00s-core-black', 41, 10),
  ('campus-00s-core-black', 42, 10),
  ('campus-00s-core-black', 43, 10),
  ('campus-00s-core-black', 44, 10),
  ('campus-00s-core-black', 45, 10),
  ('campus-00s-core-black', 46, 10),
  ('campus-00s-dark-green', 38, 10),
  ('campus-00s-dark-green', 39, 10),
  ('campus-00s-dark-green', 40, 10),
  ('campus-00s-dark-green', 41, 10),
  ('campus-00s-dark-green', 42, 10),
  ('campus-00s-dark-green', 43, 10),
  ('campus-00s-dark-green', 44, 10),
  ('campus-00s-dark-green', 45, 10),
  ('campus-00s-dark-green', 46, 10),
  ('arizona-birkenstock-taupe', 38, 10),
  ('arizona-birkenstock-taupe', 39, 10),
  ('arizona-birkenstock-taupe', 40, 10),
  ('arizona-birkenstock-taupe', 41, 10),
  ('arizona-birkenstock-taupe', 42, 10),
  ('arizona-birkenstock-taupe', 43, 10),
  ('arizona-birkenstock-taupe', 44, 10),
  ('arizona-birkenstock-taupe', 45, 10),
  ('arizona-birkenstock-taupe', 46, 10),
  ('uggs-tazz-ii-chestnut', 38, 10),
  ('uggs-tazz-ii-chestnut', 39, 10),
  ('uggs-tazz-ii-chestnut', 40, 10),
  ('uggs-tazz-ii-chestnut', 41, 10),
  ('uggs-tazz-ii-chestnut', 42, 10),
  ('uggs-tazz-ii-chestnut', 43, 10),
  ('uggs-tazz-ii-chestnut', 44, 10),
  ('uggs-tazz-ii-chestnut', 45, 10),
  ('uggs-tazz-ii-chestnut', 46, 10),
  ('uggs-tazz-ii-portobello-pink', 38, 10),
  ('uggs-tazz-ii-portobello-pink', 39, 10),
  ('uggs-tazz-ii-portobello-pink', 40, 10),
  ('uggs-tazz-ii-portobello-pink', 41, 10),
  ('uggs-tazz-ii-portobello-pink', 42, 10),
  ('uggs-tazz-ii-portobello-pink', 43, 10),
  ('uggs-tazz-ii-portobello-pink', 44, 10),
  ('uggs-tazz-ii-portobello-pink', 45, 10),
  ('uggs-tazz-ii-portobello-pink', 46, 10)
ON CONFLICT (product_id, size) DO NOTHING;
